import type { SiteConfig } from "../types";

// サンプル②：地域のお店（整体・サロン）。予約とLINE登録で集客し、回数券をオンライン販売
export const site: SiteConfig = {
  brand: { name: "からだ整え処 ひだまり", logoText: "ひだまり", tagline: "肩と腰を、根本から軽く。" },
  theme: {
    primary: "#2f6b4f",
    primaryStrong: "#24543e",
    accent: "#a1620a",
    bg: "#f8f5ef",
    surface: "#ffffff",
    ink: "#23271f",
    muted: "#5d6457",
    line: "#e4ddd0",
    dark: "#1d2a22",
    font: "mincho",
  },
  seo: {
    title: "からだ整え処 ひだまり｜肩こり・腰痛の整体（サンプル）",
    description: "一人ひとりの姿勢を見て、肩こり・腰痛を根本から整える整体院です。初回体験はオンライン予約で。",
  },
  nav: [
    { label: "特徴", href: "#features" },
    { label: "料金", href: "#pricing" },
    { label: "お客様の声", href: "#voice" },
    { label: "Q&A", href: "#faq" },
  ],
  headerCta: { label: "予約する", href: "#lead" },
  formEndpoint: "",
  contact: { email: "info@example.com", phone: "000-000-0000", hours: "10:00〜20:00（水曜定休）", lineUrl: "https://line.me/" },
  stickyCta: { label: "初回体験を予約する", href: "#lead" },
  sections: [
    {
      type: "hero",
      eyebrow: "駅から徒歩3分の整体院（サンプル）",
      title: "その{rotate}、\nあきらめなくていい。",
      rotatingWords: ["肩こり", "腰の重さ", "頭痛", "猫背"],
      lead: "マッサージで一時的にほぐすのではなく、姿勢と体の使い方から整えます。",
      primaryCta: { label: "初回体験を予約する", href: "#lead" },
      secondaryCta: { label: "LINEで相談", href: "https://line.me/" },
      image: { alt: "明るい施術室で、スタッフが姿勢をチェックしている様子" }, // src: "/images/hero.jpg" を足すと写真になる
      badges: ["初回 ¥3,980", "完全予約制", "女性スタッフ在籍"],
    },
    {
      type: "problems",
      title: "こんな方が来られています",
      items: ["デスクワークで夕方には肩がガチガチ", "朝起きると腰が痛い", "マッサージに通っても、すぐ戻る", "姿勢の悪さを指摘される"],
      answer: "原因は「こっている場所」ではなく、姿勢のくせにあることがほとんどです。",
    },
    {
      type: "features",
      id: "features",
      label: "FEATURES",
      title: "ひだまりの3つの特徴",
      items: [
        { icon: "users", title: "毎回、姿勢を写真で確認", body: "施術の前後で姿勢を撮影。変化が目で見てわかります。" },
        { icon: "heart", title: "ボキボキしない施術", body: "痛くない、やさしい施術です。初めての方も安心してどうぞ。" },
        { icon: "clock", title: "自宅でできるケアを指導", body: "1日3分のストレッチをお伝えし、良い状態を長持ちさせます。" },
      ],
    },
    {
      type: "testimonials",
      id: "voice",
      label: "VOICE",
      title: "お客様の声",
      items: [
        { quote: "3回目で、夕方の肩の重さがほとんど気にならなくなりました。", name: "30代 女性", role: "会社員（サンプル）" },
        { quote: "腰が痛くて朝がつらかったのが、今は普通に起きられます。", name: "50代 男性", role: "自営業（サンプル）" },
      ],
    },
    {
      type: "pricing",
      id: "pricing",
      label: "PRICE",
      title: "料金",
      note: "表示価格は税込・サンプルです。",
      plans: [
        { name: "初回体験", price: "¥3,980", description: "カウンセリング＋施術60分", features: ["姿勢チェック", "施術", "セルフケア指導"], ctaLabel: "予約する" },
        {
          name: "回数券（5回）",
          price: "¥27,500",
          description: "1回あたり ¥5,500",
          features: ["有効期限6か月", "ご家族と共有OK", "オンラインで購入できます"],
          checkoutUrl: "",
          ctaLabel: "オンラインで購入",
          highlight: true,
        },
        { name: "通常", price: "¥6,600", period: "/回", features: ["施術60分", "姿勢チェック"], ctaLabel: "予約する" },
      ],
    },
    {
      type: "faq",
      id: "faq",
      label: "Q&A",
      title: "よくある質問",
      items: [
        { q: "どんな服装で行けばいいですか？", a: "動きやすい服装でお越しください。着替えもご用意しています。" },
        { q: "駐車場はありますか？", a: "提携のコインパーキングがあります（サンプル）。" },
      ],
    },
    {
      type: "lead",
      id: "lead",
      label: "RESERVE",
      title: "初回体験のご予約",
      lead: "ご希望の日時を2〜3つお書きください。確認後、ご連絡します。",
      topics: ["初回体験の予約", "回数券について", "その他の相談"],
      submitLabel: "予約を送る",
    },
  ],
  legal: {
    seller: "【販売事業者名】",
    representative: "【代表者名】",
    address: "【所在地】",
    phone: "【電話番号】",
    email: "info@example.com",
    price: "料金ページに記載（税込）",
    extraFees: "なし",
    payment: "クレジットカード、店頭での現金払い",
    paymentTiming: "オンライン購入時",
    delivery: "購入後、来店時にご利用いただけます",
    returns: "未使用の回数券は購入から8日以内であれば返金します",
  },
  privacyContact: "info@example.com",
};
