import type { SiteConfig } from "../types";

// サンプル①：ホームページ制作サービス（オンラインで集客・申込・決済まで）
export const site: SiteConfig = {
  brand: { name: "TKFM Web Studio", logoText: "TKFM", tagline: "AIで速く、美しく。" },
  theme: {
    primary: "#2547d0",
    primaryStrong: "#1b36a6",
    accent: "#b45309",
    bg: "#f7f8fb",
    surface: "#ffffff",
    ink: "#141a2e",
    muted: "#55607a",
    line: "#e1e5ee",
    dark: "#0e1324",
    font: "gothic",
  },
  seo: {
    title: "TKFM Web Studio｜最短7日で、売れるホームページを。",
    description: "AIとプロのデザインで、集客と申込みまでできるホームページを最短7日で制作します。",
  },
  nav: [
    { label: "できること", href: "#features" },
    { label: "料金", href: "#pricing" },
    { label: "お客様の声", href: "#voice" },
    { label: "よくある質問", href: "#faq" },
  ],
  headerCta: { label: "無料相談", href: "#lead" },
  formEndpoint: "", // 例：https://formspree.io/f/xxxxxxx
  contact: { email: "hello@example.com", phone: "000-0000-0000", hours: "平日 10:00〜18:00", lineUrl: "" },
  analytics: { gaId: "" },
  stickyCta: { label: "まずは無料で相談する", href: "#lead" },
  sections: [
    {
      type: "hero",
      eyebrow: "ホームページ制作・リニューアル",
      title: "最短7日で、\n{rotate}が\n増えるホームページを。",
      rotatingWords: ["問い合わせ", "予約", "売上", "ファン"],
      lead: "AIで制作スピードを上げ、浮いた時間をすべて「売れる設計」に使います。作って終わりではなく、集客から申込み・決済まで一つの流れでつくります。",
      primaryCta: { label: "無料で相談する", href: "#lead" },
      secondaryCta: { label: "料金を見る", href: "#pricing" },
      image: { alt: "制作したサイトをスマホとPCで表示した画面" }, // src: "/images/hero.jpg" を足すと写真になる
      badges: ["相談・見積り無料", "スマホ対応", "公開後サポート付き"],
    },
    { type: "logos", title: "さまざまな業種で導入いただいています（サンプル）", items: ["CAFE", "SALON", "CLINIC", "SCHOOL", "STUDIO", "SHOP", "OFFICE"] },
    {
      type: "problems",
      title: "こんなお悩み、ありませんか？",
      items: [
        "ホームページはあるのに、問い合わせが来ない",
        "制作会社に頼むと高い・時間がかかる",
        "SNSは頑張っているが、売上につながらない",
        "自分で更新できず、情報が古いまま",
      ],
      answer: "その原因の多くは「見た目」ではなく「お客様が申し込むまでの流れ」にあります。",
    },
    {
      type: "features",
      id: "features",
      label: "FEATURES",
      title: "選ばれる3つの理由",
      items: [
        { icon: "zap", title: "最短7日で公開", body: "AIで下書き・コーディングを高速化。打ち合わせから公開まで最短1週間です。" },
        { icon: "trending", title: "集客から販売まで設計", body: "申込フォーム・LINE・オンライン決済まで、売上につながる導線を最初から組み込みます。" },
        { icon: "smartphone", title: "スマホで見やすい", body: "お客様の8割はスマホから。指で押しやすく、読みやすい画面に仕上げます。" },
      ],
    },
    {
      type: "stats",
      items: [
        { label: "制作実績", value: 120, unit: "件以上", note: "サンプル" },
        { label: "平均制作日数", value: 9, unit: "日", note: "サンプル" },
        { label: "問い合わせ数の伸び", value: 240, unit: "%", note: "サンプル・導入前比" },
      ],
    },
    {
      type: "testimonials",
      id: "voice",
      label: "VOICE",
      title: "お客様の声",
      items: [
        { quote: "公開した翌週から、ホームページ経由の予約が入るようになりました。", name: "A様", role: "美容室オーナー（サンプル）" },
        { quote: "LINE登録のボタンを付けてもらってから、リピーターが増えています。", name: "B様", role: "カフェ経営（サンプル）" },
        { quote: "オンライン決済ができるようになり、講座の申込みが自動化できました。", name: "C様", role: "オンライン講師（サンプル）" },
      ],
    },
    {
      type: "pricing",
      id: "pricing",
      label: "PRICE",
      title: "料金プラン",
      lead: "必要なものだけ選べます。追加費用が出る場合は、必ず事前にお見積りします。",
      note: "表示価格は税込・サンプルです。",
      plans: [
        {
          name: "ライト",
          price: "¥49,800",
          description: "まずは1ページで始めたい方に",
          features: ["1ページのLP", "スマホ対応", "問い合わせフォーム", "公開後1か月サポート"],
          checkoutUrl: "",
          ctaLabel: "このプランで申し込む",
        },
        {
          name: "スタンダード",
          price: "¥98,000",
          description: "集客から販売まで一式",
          features: ["5ページまで", "LINE・SNS連携", "オンライン決済の設置", "アクセス解析の設定", "公開後3か月サポート"],
          checkoutUrl: "",
          ctaLabel: "このプランで申し込む",
          highlight: true,
        },
        {
          name: "サポート",
          price: "¥9,800",
          period: "/月",
          description: "公開後の更新・改善をおまかせ",
          features: ["月2回までの更新", "アクセスの月次レポート", "改善の提案"],
          checkoutUrl: "",
          ctaLabel: "申し込む",
        },
      ],
    },
    {
      type: "flow",
      label: "FLOW",
      title: "公開までの流れ",
      steps: [
        { title: "無料相談", body: "フォームかLINEから。30分ほどで目的と予算を伺います。" },
        { title: "お見積り・お申込み", body: "内容に納得いただいてから、オンラインでお支払い。" },
        { title: "制作", body: "AIで下書きを作り、デザイナーが仕上げます。途中で確認いただけます。" },
        { title: "公開・サポート", body: "公開後も、数字を見ながら一緒に改善します。" },
      ],
    },
    {
      type: "faq",
      id: "faq",
      label: "FAQ",
      title: "よくある質問",
      items: [
        { q: "原稿や写真がなくても大丈夫ですか？", a: "はい。ヒアリングをもとに原稿の下書きをこちらで作成します。写真はフリー素材や撮影の手配も可能です。" },
        { q: "公開後に自分で更新できますか？", a: "できます。更新方法をお伝えするほか、月額サポートでおまかせいただくこともできます。" },
        { q: "支払い方法は？", a: "クレジットカード、銀行振込に対応しています。" },
        { q: "地方でも依頼できますか？", a: "全国対応です。打ち合わせはオンラインで行います。" },
      ],
    },
    {
      type: "lead",
      id: "lead",
      label: "CONTACT",
      title: "まずは無料で相談する",
      lead: "しつこい営業は一切しません。1営業日以内にご返信します。",
      topics: ["無料相談", "お見積り", "資料請求", "その他"],
      submitLabel: "無料で相談する",
      gift: "今なら「売れるホームページ チェックリスト」をプレゼント",
    },
    {
      type: "cta",
      title: "あなたのお店の「次のお客様」を、\nホームページで迎えにいきましょう。",
      primaryCta: { label: "無料で相談する", href: "#lead" },
      secondaryCta: { label: "料金を見る", href: "#pricing" },
    },
  ],
  legal: {
    seller: "【販売事業者名】",
    representative: "【代表者名】",
    address: "【所在地】（請求があった場合に遅滞なく開示します）",
    phone: "【電話番号】",
    email: "hello@example.com",
    price: "各プランのページに記載（税込）",
    extraFees: "銀行振込の場合の振込手数料はお客様のご負担となります",
    payment: "クレジットカード、銀行振込",
    paymentTiming: "クレジットカード：申込み時／銀行振込：申込みから7日以内",
    delivery: "お支払い確認後、打ち合わせ日程を調整し制作を開始します",
    returns: "サービスの性質上、制作開始後の返金はできません。制作開始前のキャンセルは全額返金します",
  },
  privacyContact: "hello@example.com",
};
